spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/griftt/config-server.git
          password: 1415wsh52000
          username: griftt
        force-pull: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: config
server:
  port: 8183