spring:
  application:
    name: config  #根据这名字拿到配置文件
  cloud:
    config:
      server:
        git:
          uri: https://github.com/griftt/config-server.git
          username: griftt
          password: 1415wsh52000
        force-pull: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: "*"